//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrestikNolik.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KrestikNolik.Resources.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tik Tak Toe.
        /// </summary>
        public static string MyAppTitle {
            get {
                return ResourceManager.GetString("MyAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VICTORY! Computer won!.
        /// </summary>
        public static string MyCompWin {
            get {
                return ResourceManager.GetString("MyCompWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I suggest starting the game again!.
        /// </summary>
        public static string MyIerosinuNoJauna {
            get {
                return ResourceManager.GetString("MyIerosinuNoJauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UNDRAWN ! No more moves!.
        /// </summary>
        public static string MyNoMoves {
            get {
                return ResourceManager.GetString("MyNoMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready to play!.
        /// </summary>
        public static string MyReadyGame {
            get {
                return ResourceManager.GetString("MyReadyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start playing again!.
        /// </summary>
        public static string MyStartAgain {
            get {
                return ResourceManager.GetString("MyStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Victory! You are win!.
        /// </summary>
        public static string MyVictory {
            get {
                return ResourceManager.GetString("MyVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X-computer VS 0-Man.
        /// </summary>
        public static string XdatorsVSOman {
            get {
                return ResourceManager.GetString("XdatorsVSOman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X-Man VS 0-Computer.
        /// </summary>
        public static string XmanVSdators {
            get {
                return ResourceManager.GetString("XmanVSdators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X-Man VS 0-Man.
        /// </summary>
        public static string XmanVSOman {
            get {
                return ResourceManager.GetString("XmanVSOman", resourceCulture);
            }
        }
    }
}
